# Generated by Django 5.2.10 on 2026-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidencecategory_primary_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencecategory',
            name='review_period',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('DAILY_WEEKLY', 'Daily/Weekly'), ('WEEKLY_MONTHLY', 'Weekly/Monthly'), ('MONTHLY', 'Monthly'), ('REGULAR', 'Regular'), ('REGULAR_MONTHLY', 'Regular - meeting monthly'), ('MONTHLY_QUARTERLY', 'Monthly/Quarterly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY_QUARTERLY', 'Half yearly/Quarterly'), ('QUARTERLY_HALFYEARLY_ANNUALLY', 'Quarterly/Halfyearly/Annually'), ('ANNUALLY', 'Annually')], max_length=50),
        ),
    ]
