# Generated by Django 5.2.10 on 2026-01-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_alter_evidencecategory_review_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencecategory',
            name='category_group',
            field=models.CharField(choices=[('ACCESS_CONTROLS', 'Access Controls'), ('NETWORK_SECURITY', 'Network Security'), ('PHYSICAL_SECURITY', 'Physical Security'), ('DATA_PROTECTION', 'Data Protection'), ('ENDPOINT_SECURITY', 'Endpoint Security'), ('MONITORING_INCIDENT', 'Monitoring & Incident Response'), ('INFRASTRUCTURE_CAPACITY', 'Infrastructure & Capacity'), ('BACKUP_RECOVERY', 'Backup & Recovery'), ('BUSINESS_CONTINUITY', 'Business Continuity'), ('CONFIDENTIALITY', 'Confidentiality'), ('CONTROL_ENVIRONMENT', 'Control Environment (CC1)'), ('COMMUNICATION_INFO', 'Communication & Information (CC2)'), ('RISK_ASSESSMENT', 'Risk Assessment (CC3)'), ('MONITORING', 'Monitoring (CC4)'), ('HR_TRAINING', 'Control Activities - HR & Training (CC5)'), ('CHANGE_MANAGEMENT', 'Control Activities - Change Management (CC5)'), ('VENDOR_MANAGEMENT', 'Control Activities - Vendor Management (CC5)'), ('UNCATEGORIZED', 'Uncategorized')], default='UNCATEGORIZED', max_length=50),
        ),
    ]
