# Generated by Django 5.2.10 on 2026-01-09 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_alter_evidencecategory_review_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencecategory',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='Person who approves submissions for this control', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencecategory',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='Person responsible for this control', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_controls', to=settings.AUTH_USER_MODEL),
        ),
    ]
