# Generated by Django 5.2.10 on 2026-01-09 10:47

import evidence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0006_evidencecategory_approver_evidencecategory_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=evidence.models.evidence_file_upload_path),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='google_drive_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
