# Generated by Django 5.2.10 on 2026-01-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DUE_SOON', 'Due Soon'), ('OVERDUE', 'Overdue'), ('PENDING_APPROVAL', 'Pending Approval'), ('CONTROL_ASSIGNED', 'Control Assigned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
