# Generated by Django 5.2.10 on 2026-01-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveFolderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('security_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('availability_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('confidentiality_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('common_criteria_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category_group_folder_ids', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Drive Folder Mapping',
                'verbose_name_plural': 'Google Drive Folder Mappings',
            },
        ),
    ]
